### ISSUE TITLE
Mounting on linux systems using KDE

### ISSUE THREAD

**Issue by infeo** [cryptomator/webdav-nio-adapter#34]
## Description
Even if gio or gvfs is installed on the regarding system, if one uses KDE as the desktop environment a filesystem cannot be mounted. By calling `mount()`, the following stacktrace is shown:

```
Caused by: org.cryptomator.frontend.webdav.mount.Mounter$CommandFailedException: Command failed with exit code 2. Expected 0. Stderr: gio: webdav://localhost:42427/qbZJ29z6d546/asd: volume doesn’t implement mount

	at org.cryptomator.frontend.webdav.mount.ProcessUtil.assertExitValue(ProcessUtil.java:28)
	at org.cryptomator.frontend.webdav.mount.LinuxGioMounter.mount(LinuxGioMounter.java:39)
	at org.cryptomator.frontend.webdav.servlet.WebDavServletController.mount(WebDavServletController.java:102)
	at org.cryptomator.common.vaults.WebDavVolume.mount(WebDavVolume.java:62)
	... 12 more
```

The adapter uses the [gio](https://developer.gnome.org/gio/stable/) tool to mount the (local) network location, but for KDE it relied on the quite old and unmainted KIO-GIO package, which seems to lost functionality in newer KDE versions.

The problem of mounting network locations with KDE persisted for a long time, see https://bugs.kde.org/show_bug.cgi?id=75324. Since beginning of this year there exists a new approach with [KIO-FUSE](https://github.com/KDE/kio-fuse), but it is not included in the standard packages sources yet (and does not look 100% stable).

## Remark
This is the upstream issue for https://github.com/cryptomator/cryptomator/issues/1381

**Comment by overheadhunter** [comment]
https://bugs.kde.org/show_bug.cgi?id=75324 is now fixed. Can we re-enable mounting via gvfs on KDE?

**Comment by infeo** [comment]
If we implement a new mounter which uses kio-fuse, then mounting on KDE can be re-enabled. The gio/gvfs mounter are not applicable anymore for KDE, see the discussion in the KDE issue.

**Comment by overheadhunter** [comment]
I see. Well not a high prio issue, since FUSE is included in basically every Linux nowadays.
